# Problem 1 

In [5]:
# 1 - numpy kütüphanesini import edin

import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun

array = np.array([5,4,3,2,1])

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.

siralanmisArray=np.sort(array)

print("Orijinal array:", array)
print("Sıralanmış array:", siralanmisArray)


Orijinal array: [5 4 3 2 1]
Sıralanmış array: [1 2 3 4 5]


# Problem 2

In [9]:
import numpy as ny

# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.

dizi1=np.array([10,15,30,45,60])
print("Dizi1:", dizi1)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.

dizi2=np.arange(5,16)
print("Dizi2:", dizi2)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.

dizi3=np.arange(50,101,5)
print("Dizi3:", dizi3)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.

dizi4=np.zeros(10)
print("Dizi4:", dizi4)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.

dizi5=np.ones(10)
print("Dizi5:", dizi5)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.

dizi6=np.linspace(0,101,5)
print("Dizi6:", dizi6)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.

dizi7=np.random.randint(10,31,5)
print("Dizi7:", dizi7)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.

dizi8=np.random.uniform(-1,1,5) # unifrom ile float sayi
print("Dizi8:", dizi8)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.

matris= np.random.randint(10,51,(3,5))
print("Matris:", matris)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?

satirToplamlari = np.sum(matris, axis=1) #axis=1 demek, yatay eksen boyunca (satır bazında) toplamı hesapla demek
sutunToplamlari = np.sum(matris, axis=0) #axis=0 demek, dikey eksen boyunca (sütun bazında) toplamı hesapla demek
print("Satır Toplamları:", satirToplamlari)
print("Sütun Toplamları:", sutunToplamlari)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?

enBuyuk = np.max(matris)
enKucuk = np.min(matris)
ortalama = np.mean(matris)
print("En Büyük:", enBuyuk)
print("En Küçük:", enKucuk)
print("Ortalama:", ortalama)

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?

enBuyukIndeksi = np.unravel_index(np.argmax(matris), matris.shape)
print("En Büyük Değerin İndeksi:", enBuyukIndeksi)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.

dizi13 = np.arange(10, 21)[:3]
print("Dizi13:", dizi13)

# 14- Üretilen dizinin elemanlarını tersten yazdırın.

tersDizi13 = dizi13[::-1]
print("Ters Dizi13:", tersDizi13) #[::-1]: Bu ifade, diziyi tersten (sağdan sola) okuyarak yeni bir dizi oluşturuyor

# 15- Üretilen matrisin ilk satırını seçiniz.

ilkSatir = matris[0]
print("İlk Satır:", ilkSatir)

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?

eleman_2_3 = matris[1, 2]
print("2. Satır 3. Sütun Elemanı:", eleman_2_3)

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.

ilkElemanlar = matris[:, 0]
print("İlk Elemanlar:", ilkElemanlar)

# 18- Üretilen matrisin her bir elemanının karesini alınız.

matrisKaresi = np.square(matris)
print("Matrisin Karesi:\n", matrisKaresi)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.

matris2 = np.random.randint(-50, 51, (3, 5))
pozitifCiftler = matris2[(matris2 > 0) & (matris2 % 2 == 0)]
print("Pozitif Çift Sayılar:", pozitifCiftler)

Dizi1: [10 15 30 45 60]
Dizi2: [ 5  6  7  8  9 10 11 12 13 14 15]
Dizi3: [ 50  55  60  65  70  75  80  85  90  95 100]
Dizi4: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Dizi5: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Dizi6: [  0.    25.25  50.5   75.75 101.  ]
Dizi7: [28 11 24 29 28]
Dizi8: [-0.84833536  0.93905874 -0.34140054  0.42114418 -0.69774388]
Matris: [[13 24 37 23 27]
 [14 12 44 14 48]
 [14 19 33 23 16]]
Satır Toplamları: [124 132 105]
Sütun Toplamları: [ 41  55 114  60  91]
En Büyük: 48
En Küçük: 12
Ortalama: 24.066666666666666
En Büyük Değerin İndeksi: (np.int64(1), np.int64(4))
Dizi13: [10 11 12]
Ters Dizi13: [12 11 10]
İlk Satır: [13 24 37 23 27]
2. Satır 3. Sütun Elemanı: 44
İlk Elemanlar: [13 14 14]
Matrisin Karesi:
 [[ 169  576 1369  529  729]
 [ 196  144 1936  196 2304]
 [ 196  361 1089  529  256]]
Pozitif Çift Sayılar: []
